services:
  - type: web
    name: gold-news-alerts
    env: python
    buildCommand: |
  apt-get update && apt-get install -y wget unzip gnupg2
  wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  apt install -y ./google-chrome-stable_current_amd64.deb
  pip install -r requirements.txt
startCommand: gunicorn app:app --bind 0.0.0.0:$PORT

    envVars:
      - key: PORT
        value: 10000
